//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 扩展类型请使用partial关键字在其他文件扩展，否则更改可能会丢失。
namespace Accelbuffer.Compiling
{
    using Accelbuffer;
    using Accelbuffer.Injection;
    using Accelbuffer.Memory;
    using System;
    using System.Collections.Generic;
    using boolean = System.Boolean;
    using int8 = System.SByte;
    using uint8 = System.Byte;
    using int16 = System.Int16;
    using uint16 = System.UInt16;
    using int32 = System.Int32;
    using uint32 = System.UInt32;
    using int64 = System.Int64;
    using uint64 = System.UInt64;
    using float32 = System.Single;
    using float64 = System.Double;
    using float128 = System.Decimal;
    using nint = System.IntPtr;
    using nuint = System.UIntPtr;
    using vint = Accelbuffer.VInt;
    using vuint = Accelbuffer.VUInt;
    
    
    /// <summary>
    /// 类型名称
    /// </summary>
    [MemorySize(120)]
    [SerializeBy(typeof(TypeName.TypeNameSerializer))]
    public partial class TypeName
    {
        
        [SerialIndex(1)]
        private string m_RawString;
        
        [SerialIndex(2)]
        private string m_RawStringWithoutNullableAndArraySuffix;
        
        [NeverNull()]
        [SerialIndex(3)]
        private boolean m_IsGenericType;
        
        [SerialIndex(4)]
        private TypeName m_GenericTypeDefinitionName;
        
        [SerialIndex(5)]
        private TypeName[] m_GenericParameters;
        
        [NeverNull()]
        [SerialIndex(6)]
        private boolean m_IsNullable;
        
        [NeverNull()]
        [SerialIndex(7)]
        private vint m_ArraySuffixCount;
        
partial void OnBeforeSerialization();
partial void OnAfterDeserialization();
        
        /// <summary>
        /// 类型名称的原始字符串
        /// </summary>
        public string RawString
        {
            get
            {
                return this.m_RawString;
            }
            set
            {
                this.m_RawString = value;
            }
        }
        
        /// <summary>
        /// 类型名称的原始字符串没有nullable符号和数组后缀
        /// </summary>
        public string RawStringWithoutNullableAndArraySuffix
        {
            get
            {
                return this.m_RawStringWithoutNullableAndArraySuffix;
            }
            set
            {
                this.m_RawStringWithoutNullableAndArraySuffix = value;
            }
        }
        
        /// <summary>
        /// 获取类型是否为泛型
        /// </summary>
        public boolean IsGenericType
        {
            get
            {
                return this.m_IsGenericType;
            }
            set
            {
                this.m_IsGenericType = value;
            }
        }
        
        /// <summary>
        /// 获取类型的泛型定义名称
        /// </summary>
        public TypeName GenericTypeDefinitionName
        {
            get
            {
                return this.m_GenericTypeDefinitionName;
            }
            set
            {
                this.m_GenericTypeDefinitionName = value;
            }
        }
        
        /// <summary>
        /// 获取类型的泛型参数
        /// </summary>
        public TypeName[] GenericParameters
        {
            get
            {
                return this.m_GenericParameters;
            }
            set
            {
                this.m_GenericParameters = value;
            }
        }
        
        /// <summary>
        /// 获取类型是否是可以为空的类型
        /// </summary>
        public boolean IsNullable
        {
            get
            {
                return this.m_IsNullable;
            }
            set
            {
                this.m_IsNullable = value;
            }
        }
        
        /// <summary>
        /// 获取类型的数组后缀数量
        /// </summary>
        public vint ArraySuffixCount
        {
            get
            {
                return this.m_ArraySuffixCount;
            }
            set
            {
                this.m_ArraySuffixCount = value;
            }
        }
        
        /// <summary>
        /// 序列化对象
        /// </summary>
        public byte[] ToBytes()
        {
            byte[] result;
            Serializer.Serialize(this, out result);
            return result;
        }
        
        /// <summary>
        /// 反序列化对象
        /// </summary>
        public static TypeName FromBytes(byte[] bytes)
        {
return Serializer.Deserialize<TypeName>(bytes, 0, bytes.Length);
        }
        
        /// <summary>
        /// 对象序列化代理（自动生成）
        /// </summary>
        public sealed class TypeNameSerializer : object, ITypeSerializer<TypeName>
        {
            
            /// <summary>
            /// 序列化方法（自动生成）
            /// </summary>
            public void Serialize(TypeName obj, ref AccelWriter writer)
            {
                obj.OnBeforeSerialization();
                if ((obj.m_RawString != null))
                {
                    writer.WriteValue(1, obj.m_RawString);
                }
                if ((obj.m_RawStringWithoutNullableAndArraySuffix != null))
                {
                    writer.WriteValue(2, obj.m_RawStringWithoutNullableAndArraySuffix);
                }
                writer.WriteValue(3, obj.m_IsGenericType);
                if ((obj.m_GenericTypeDefinitionName != null))
                {
                    writer.WriteValue(4, obj.m_GenericTypeDefinitionName);
                }
                if ((obj.m_GenericParameters != null))
                {
                    writer.WriteValue(5, obj.m_GenericParameters);
                }
                writer.WriteValue(6, obj.m_IsNullable);
                writer.WriteValue(7, obj.m_ArraySuffixCount);
            }
            
            /// <summary>
            /// 反序列化方法（自动生成）
            /// </summary>
            public TypeName Deserialize(ref AccelReader reader)
            {
                TypeName result = new TypeName();
                int index;
			while (reader.HasNext(out index))
			{
				switch (index)
				{
					case 1:
						result.m_RawString = reader.ReadString();
						break;
					case 2:
						result.m_RawStringWithoutNullableAndArraySuffix = reader.ReadString();
						break;
					case 3:
						result.m_IsGenericType = reader.ReadBoolean();
						break;
					case 4:
						result.m_GenericTypeDefinitionName = reader.ReadGeneric<TypeName>();
						break;
					case 5:
						result.m_GenericParameters = reader.ReadGeneric<TypeName[]>();
						break;
					case 6:
						result.m_IsNullable = reader.ReadBoolean();
						break;
					case 7:
						result.m_ArraySuffixCount = reader.ReadVariantInt();
						break;
					default:
						reader.SkipNext();
						break;
				}
			}

                result.OnAfterDeserialization();
                return result;
            }
        }
    }
}
