//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     编译器版本:v0.1.0.5
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Accelbuffer;
using Accelbuffer.Injection;
using Accelbuffer.Memory;
using Accelbuffer.Text;
using System;
using System.Collections.Generic;
using ProtoBuf;

namespace Accelbuffer.Test
{

	[Serializable]
    [CompactLayout]
	[InitialMemorySize(200)]
    [ProtoContract]
	public struct Test
	{
        [ProtoMember(1)]
		[FieldIndex(1)]
		[Encoding(Encoding.UTF8)]
		public string StringValue;
        [ProtoMember(2)]
        [FieldIndex(2)]
		public int Int32Value;
        [ProtoMember(3)]
        [FieldIndex(3)]
		public List<Test1> ListValue;
	}

	[Serializable]
    [CompactLayout]
    [InitialMemorySize(200)]
    [ProtoContract]
    public struct Test1
	{
        [ProtoMember(1)]
        [FieldIndex(1)]
		public float FloatValue;
        [ProtoMember(2)]
        [FieldIndex(2)]
		public Dictionary<string, int> DictValue;
	}
}
