//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accelbuffer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accelbuffer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ASCII字符串的字节数量必须是非负数 的本地化字符串。
        /// </summary>
        internal static string ASCIIStringByteCountError {
            get {
                return ResourceManager.GetString("ASCIIStringByteCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boolean 的本地化字符串。
        /// </summary>
        internal static string BoolName {
            get {
                return ResourceManager.GetString("BoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节数组不能为空 的本地化字符串。
        /// </summary>
        internal static string ByteArrayIsNull {
            get {
                return ResourceManager.GetString("ByteArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节数组长度过小 的本地化字符串。
        /// </summary>
        internal static string ByteArrayTooShort {
            get {
                return ResourceManager.GetString("ByteArrayTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UInt8 的本地化字符串。
        /// </summary>
        internal static string ByteName {
            get {
                return ResourceManager.GetString("ByteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Char 的本地化字符串。
        /// </summary>
        internal static string CharName {
            get {
                return ResourceManager.GetString("CharName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ComplexName {
            get {
                return ResourceManager.GetString("ComplexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float128 的本地化字符串。
        /// </summary>
        internal static string DecimalName {
            get {
                return ResourceManager.GetString("DecimalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deserialize 的本地化字符串。
        /// </summary>
        internal static string DeserializeMethodName {
            get {
                return ResourceManager.GetString("DeserializeMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float64 的本地化字符串。
        /// </summary>
        internal static string DoubleName {
            get {
                return ResourceManager.GetString("DoubleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float32 的本地化字符串。
        /// </summary>
        internal static string FloatName {
            get {
                return ResourceManager.GetString("FloatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HasNext 的本地化字符串。
        /// </summary>
        internal static string HasNextName {
            get {
                return ResourceManager.GetString("HasNextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Int32 的本地化字符串。
        /// </summary>
        internal static string IntName {
            get {
                return ResourceManager.GetString("IntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在从{0}到{1}的隐式转换 的本地化字符串。
        /// </summary>
        internal static string InvalidCastFormat {
            get {
                return ResourceManager.GetString("InvalidCastFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段的索引必须是 (0, 268435456] 范围内的整数 的本地化字符串。
        /// </summary>
        internal static string InvalidFieldIndex {
            get {
                return ResourceManager.GetString("InvalidFieldIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有的序列化代理必须要实现ITypeSerializer&lt;T&gt;接口 的本地化字符串。
        /// </summary>
        internal static string InvalidSerializerType {
            get {
                return ResourceManager.GetString("InvalidSerializerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTF8字符的第一个字节的格式必须满足&apos;0vvvvvvv&apos;或&apos;110vvvvv&apos;或&apos;1110vvvv&apos; 的本地化字符串。
        /// </summary>
        internal static string InvalidUTF8Char {
            get {
                return ResourceManager.GetString("InvalidUTF8Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Int64 的本地化字符串。
        /// </summary>
        internal static string LongName {
            get {
                return ResourceManager.GetString("LongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NextAs 的本地化字符串。
        /// </summary>
        internal static string NextAsName {
            get {
                return ResourceManager.GetString("NextAsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NextAs{0}WithoutTag 的本地化字符串。
        /// </summary>
        internal static string NextAsWithoutTagName {
            get {
                return ResourceManager.GetString("NextAsWithoutTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法为{0}类型注入代理，因为类型没有被标记为[Serializable] 的本地化字符串。
        /// </summary>
        internal static string NotSerializable {
            get {
                return ResourceManager.GetString("NotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持多维数组序列化与反序列化 的本地化字符串。
        /// </summary>
        internal static string NotSupportHighRankArray {
            get {
                return ResourceManager.GetString("NotSupportHighRankArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法为{0}类型注入代理，因为类型没有无参构造方法 的本地化字符串。
        /// </summary>
        internal static string NotSupportTypeInjection {
            get {
                return ResourceManager.GetString("NotSupportTypeInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Int8 的本地化字符串。
        /// </summary>
        internal static string SByteName {
            get {
                return ResourceManager.GetString("SByteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serialize 的本地化字符串。
        /// </summary>
        internal static string SerializeMethodName {
            get {
                return ResourceManager.GetString("SerializeMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DynamicSerializerAssembly.dll 的本地化字符串。
        /// </summary>
        internal static string SerializerAssemblyName {
            get {
                return ResourceManager.GetString("SerializerAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DynamicSerializerModule 的本地化字符串。
        /// </summary>
        internal static string SerializerModuleName {
            get {
                return ResourceManager.GetString("SerializerModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列化代理类型不能为null 的本地化字符串。
        /// </summary>
        internal static string SerializerTypeIsNull {
            get {
                return ResourceManager.GetString("SerializerTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Serializer&gt; 的本地化字符串。
        /// </summary>
        internal static string SerializerTypeSuffix {
            get {
                return ResourceManager.GetString("SerializerTypeSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Int16 的本地化字符串。
        /// </summary>
        internal static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SkipNext 的本地化字符串。
        /// </summary>
        internal static string SkipNextName {
            get {
                return ResourceManager.GetString("SkipNextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据流的长度过小 的本地化字符串。
        /// </summary>
        internal static string StreamTooShort {
            get {
                return ResourceManager.GetString("StreamTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String 的本地化字符串。
        /// </summary>
        internal static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UInt32 的本地化字符串。
        /// </summary>
        internal static string UIntName {
            get {
                return ResourceManager.GetString("UIntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UInt64 的本地化字符串。
        /// </summary>
        internal static string ULongName {
            get {
                return ResourceManager.GetString("ULongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unicode字符串的字节数量必须是非负偶数 的本地化字符串。
        /// </summary>
        internal static string UnicodeStringByteCountError {
            get {
                return ResourceManager.GetString("UnicodeStringByteCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UInt16 的本地化字符串。
        /// </summary>
        internal static string UShortName {
            get {
                return ResourceManager.GetString("UShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTF8字符串的字节数量必须是非负数 的本地化字符串。
        /// </summary>
        internal static string UTF8StringByteCountError {
            get {
                return ResourceManager.GetString("UTF8StringByteCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WriteValue 的本地化字符串。
        /// </summary>
        internal static string WriteValueMethodName {
            get {
                return ResourceManager.GetString("WriteValueMethodName", resourceCulture);
            }
        }
    }
}
