//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accelbuffer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accelbuffer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ASCII字符串的字节数量必须是非负数 的本地化字符串。
        /// </summary>
        internal static string ASCIIStringByteCountError {
            get {
                return ResourceManager.GetString("ASCIIStringByteCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boolean 的本地化字符串。
        /// </summary>
        internal static string BoolName {
            get {
                return ResourceManager.GetString("BoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节数组不能为空 的本地化字符串。
        /// </summary>
        internal static string ByteArrayIsNull {
            get {
                return ResourceManager.GetString("ByteArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字节数组长度过小 的本地化字符串。
        /// </summary>
        internal static string ByteArrayTooShort {
            get {
                return ResourceManager.GetString("ByteArrayTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UInt8 的本地化字符串。
        /// </summary>
        internal static string ByteName {
            get {
                return ResourceManager.GetString("ByteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Char 的本地化字符串。
        /// </summary>
        internal static string CharName {
            get {
                return ResourceManager.GetString("CharName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color32 的本地化字符串。
        /// </summary>
        internal static string Color32Name {
            get {
                return ResourceManager.GetString("Color32Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        internal static string ColorName {
            get {
                return ResourceManager.GetString("ColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float128 的本地化字符串。
        /// </summary>
        internal static string DecimalName {
            get {
                return ResourceManager.GetString("DecimalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deserialize 的本地化字符串。
        /// </summary>
        internal static string DeserializeMethodName {
            get {
                return ResourceManager.GetString("DeserializeMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float64 的本地化字符串。
        /// </summary>
        internal static string DoubleName {
            get {
                return ResourceManager.GetString("DoubleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS001: invalid character: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS001_InvalidChar {
            get {
                return ResourceManager.GetString("Error_AS001_InvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS002: missing &apos;--&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS002_MissingDocEnd {
            get {
                return ResourceManager.GetString("Error_AS002_MissingDocEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS003: missing identifier 的本地化字符串。
        /// </summary>
        internal static string Error_AS003_MissingIdentifier {
            get {
                return ResourceManager.GetString("Error_AS003_MissingIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS004: missing &apos;;&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS004_MissingSemicolon {
            get {
                return ResourceManager.GetString("Error_AS004_MissingSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS005: invalid identifier: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS005_InvalidIdentifier {
            get {
                return ResourceManager.GetString("Error_AS005_InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS006: package declaration should be the first non empty statement of the file 的本地化字符串。
        /// </summary>
        internal static string Error_AS006_InvalidPackage {
            get {
                return ResourceManager.GetString("Error_AS006_InvalidPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS007: invalid token: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS007_InvalidToken {
            get {
                return ResourceManager.GetString("Error_AS007_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS008: duplicate keyword: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS008_MultipleKeyword {
            get {
                return ResourceManager.GetString("Error_AS008_MultipleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS009: duplicate access modifier 的本地化字符串。
        /// </summary>
        internal static string Error_AS009_MultipleAccessKeyword {
            get {
                return ResourceManager.GetString("Error_AS009_MultipleAccessKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS010: only structures marked with the &apos;ref&apos; keyword can be marked as&apos; final &apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS010_InvalidFinalKeyword {
            get {
                return ResourceManager.GetString("Error_AS010_InvalidFinalKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS011: missing integer value 的本地化字符串。
        /// </summary>
        internal static string Error_AS011_MissingIntLiteral {
            get {
                return ResourceManager.GetString("Error_AS011_MissingIntLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS012: missing &apos;{{&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS012_MissingOpenBrace {
            get {
                return ResourceManager.GetString("Error_AS012_MissingOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS013: field index must be in range (0, 268435456] 的本地化字符串。
        /// </summary>
        internal static string Error_AS013_InvalidFieldIndex {
            get {
                return ResourceManager.GetString("Error_AS013_InvalidFieldIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS014: missing &apos;:&apos; or &apos;|&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS014_MissingColonOrBar {
            get {
                return ResourceManager.GetString("Error_AS014_MissingColonOrBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS015: missing &apos;;&apos; or &apos;obsolete&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS015_MissingSemicolonOrObsoleteKeyword {
            get {
                return ResourceManager.GetString("Error_AS015_MissingSemicolonOrObsoleteKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS016: missing identifier or &apos;*&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS016_MissingIdentifierOrAsterisk {
            get {
                return ResourceManager.GetString("Error_AS016_MissingIdentifierOrAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS017: missing &apos;}}&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS017_MissingCloseBrace {
            get {
                return ResourceManager.GetString("Error_AS017_MissingCloseBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS018: keyword &apos;private&apos; can only be used in nested types 的本地化字符串。
        /// </summary>
        internal static string Error_AS018_InvalidPrivateKeyword {
            get {
                return ResourceManager.GetString("Error_AS018_InvalidPrivateKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS019: keyword &apos;protected&apos; can only be used in nested types 的本地化字符串。
        /// </summary>
        internal static string Error_AS019_InvalidProtectedKeyword {
            get {
                return ResourceManager.GetString("Error_AS019_InvalidProtectedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS020: duplicate field index &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS020_MultipleIndex {
            get {
                return ResourceManager.GetString("Error_AS020_MultipleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS021: missing &apos;)&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS021_MissingCloseParen {
            get {
                return ResourceManager.GetString("Error_AS021_MissingCloseParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float32 的本地化字符串。
        /// </summary>
        internal static string FloatName {
            get {
                return ResourceManager.GetString("FloatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generic 的本地化字符串。
        /// </summary>
        internal static string GenericName {
            get {
                return ResourceManager.GetString("GenericName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HasNext 的本地化字符串。
        /// </summary>
        internal static string HasNextName {
            get {
                return ResourceManager.GetString("HasNextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Int32 的本地化字符串。
        /// </summary>
        internal static string IntName {
            get {
                return ResourceManager.GetString("IntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IntPtr 的本地化字符串。
        /// </summary>
        internal static string IntPtrName {
            get {
                return ResourceManager.GetString("IntPtrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在从{0}到{1}的隐式转换 的本地化字符串。
        /// </summary>
        internal static string InvalidCastFormat {
            get {
                return ResourceManager.GetString("InvalidCastFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段的索引必须是 (0, 268435456] 范围内的整数 的本地化字符串。
        /// </summary>
        internal static string InvalidFieldIndex {
            get {
                return ResourceManager.GetString("InvalidFieldIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有的序列化代理必须要实现ITypeSerializer&lt;T&gt;接口 的本地化字符串。
        /// </summary>
        internal static string InvalidSerializerType {
            get {
                return ResourceManager.GetString("InvalidSerializerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTF8字符的第一个字节的格式必须满足&apos;0vvvvvvv&apos;或&apos;110vvvvv&apos;或&apos;1110vvvv&apos; 的本地化字符串。
        /// </summary>
        internal static string InvalidUTF8Char {
            get {
                return ResourceManager.GetString("InvalidUTF8Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Int64 的本地化字符串。
        /// </summary>
        internal static string LongName {
            get {
                return ResourceManager.GetString("LongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持多维数组序列化与反序列化 的本地化字符串。
        /// </summary>
        internal static string NotSupportHighRankArray {
            get {
                return ResourceManager.GetString("NotSupportHighRankArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法为{0}类型注入代理，因为类型没有无参构造方法 的本地化字符串。
        /// </summary>
        internal static string NotSupportTypeInjection {
            get {
                return ResourceManager.GetString("NotSupportTypeInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quaternion 的本地化字符串。
        /// </summary>
        internal static string QuaternionName {
            get {
                return ResourceManager.GetString("QuaternionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read 的本地化字符串。
        /// </summary>
        internal static string ReadName {
            get {
                return ResourceManager.GetString("ReadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RuntimeTypes.dll 的本地化字符串。
        /// </summary>
        internal static string RuntimeAssemblyName {
            get {
                return ResourceManager.GetString("RuntimeAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RuntimeTypesModule 的本地化字符串。
        /// </summary>
        internal static string RuntimeModuleName {
            get {
                return ResourceManager.GetString("RuntimeModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DynamicAssembly.dll 的本地化字符串。
        /// </summary>
        internal static string SavedAssemblyName {
            get {
                return ResourceManager.GetString("SavedAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Int8 的本地化字符串。
        /// </summary>
        internal static string SByteName {
            get {
                return ResourceManager.GetString("SByteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serialize 的本地化字符串。
        /// </summary>
        internal static string SerializeMethodName {
            get {
                return ResourceManager.GetString("SerializeMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列化代理类型不能为null 的本地化字符串。
        /// </summary>
        internal static string SerializerTypeIsNull {
            get {
                return ResourceManager.GetString("SerializerTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serializer 的本地化字符串。
        /// </summary>
        internal static string SerializerTypeSuffix {
            get {
                return ResourceManager.GetString("SerializerTypeSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Int16 的本地化字符串。
        /// </summary>
        internal static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SkipNext 的本地化字符串。
        /// </summary>
        internal static string SkipNextName {
            get {
                return ResourceManager.GetString("SkipNextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据流的长度过小 的本地化字符串。
        /// </summary>
        internal static string StreamTooShort {
            get {
                return ResourceManager.GetString("StreamTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String 的本地化字符串。
        /// </summary>
        internal static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UInt32 的本地化字符串。
        /// </summary>
        internal static string UIntName {
            get {
                return ResourceManager.GetString("UIntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UIntPtr 的本地化字符串。
        /// </summary>
        internal static string UIntPtrName {
            get {
                return ResourceManager.GetString("UIntPtrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UInt64 的本地化字符串。
        /// </summary>
        internal static string ULongName {
            get {
                return ResourceManager.GetString("ULongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unicode字符串的字节数量必须是非负偶数 的本地化字符串。
        /// </summary>
        internal static string UnicodeStringByteCountError {
            get {
                return ResourceManager.GetString("UnicodeStringByteCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UInt16 的本地化字符串。
        /// </summary>
        internal static string UShortName {
            get {
                return ResourceManager.GetString("UShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTF8字符串的字节数量必须是非负数 的本地化字符串。
        /// </summary>
        internal static string UTF8StringByteCountError {
            get {
                return ResourceManager.GetString("UTF8StringByteCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vector2Int 的本地化字符串。
        /// </summary>
        internal static string Vector2IntName {
            get {
                return ResourceManager.GetString("Vector2IntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vector2 的本地化字符串。
        /// </summary>
        internal static string Vector2Name {
            get {
                return ResourceManager.GetString("Vector2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vector3Int 的本地化字符串。
        /// </summary>
        internal static string Vector3IntName {
            get {
                return ResourceManager.GetString("Vector3IntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vector3 的本地化字符串。
        /// </summary>
        internal static string Vector3Name {
            get {
                return ResourceManager.GetString("Vector3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vector4 的本地化字符串。
        /// </summary>
        internal static string Vector4Name {
            get {
                return ResourceManager.GetString("Vector4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v0.1.6.14 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v0.1.6.14 unity 的本地化字符串。
        /// </summary>
        internal static string Version_Unity {
            get {
                return ResourceManager.GetString("Version_Unity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VariantInt 的本地化字符串。
        /// </summary>
        internal static string VIntName {
            get {
                return ResourceManager.GetString("VIntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VariantUInt 的本地化字符串。
        /// </summary>
        internal static string VUIntName {
            get {
                return ResourceManager.GetString("VUIntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 warning: AS001: the memory size required for the structure must be greater than 0 的本地化字符串。
        /// </summary>
        internal static string Warning_AS001_InvalidMemorySize {
            get {
                return ResourceManager.GetString("Warning_AS001_InvalidMemorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 warning: AS002: package &apos;{0}&apos; will be referenced automatically, no need to manually reference again 的本地化字符串。
        /// </summary>
        internal static string Warning_AS002_UnnecessaryUsing {
            get {
                return ResourceManager.GetString("Warning_AS002_UnnecessaryUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 warning: AS003: the indexes of fields should be as continuous as possible 的本地化字符串。
        /// </summary>
        internal static string Warning_AS003_RequireContinuousIndex {
            get {
                return ResourceManager.GetString("Warning_AS003_RequireContinuousIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WriteValue 的本地化字符串。
        /// </summary>
        internal static string WriteValueMethodName {
            get {
                return ResourceManager.GetString("WriteValueMethodName", resourceCulture);
            }
        }
    }
}
