//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace asc.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS001: invalid character: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS001_InvalidChar {
            get {
                return ResourceManager.GetString("Error_AS001_InvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS002: missing &apos;--&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS002_MissingDocEnd {
            get {
                return ResourceManager.GetString("Error_AS002_MissingDocEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS003: missing identifier 的本地化字符串。
        /// </summary>
        internal static string Error_AS003_MissingIdentifier {
            get {
                return ResourceManager.GetString("Error_AS003_MissingIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS004: missing &apos;;&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS004_MissingSemicolon {
            get {
                return ResourceManager.GetString("Error_AS004_MissingSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS005: invalid identifier: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS005_InvalidIdentifier {
            get {
                return ResourceManager.GetString("Error_AS005_InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS006: package declaration should be the first non empty statement of the file 的本地化字符串。
        /// </summary>
        internal static string Error_AS006_InvalidPackage {
            get {
                return ResourceManager.GetString("Error_AS006_InvalidPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS007: invalid token: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS007_InvalidToken {
            get {
                return ResourceManager.GetString("Error_AS007_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS008: duplicate keyword: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS008_MultipleKeyword {
            get {
                return ResourceManager.GetString("Error_AS008_MultipleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS009: duplicate access modifier 的本地化字符串。
        /// </summary>
        internal static string Error_AS009_MultipleAccessKeyword {
            get {
                return ResourceManager.GetString("Error_AS009_MultipleAccessKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS010: only structures marked with the &apos;ref&apos; keyword can be marked as&apos; final &apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS010_InvalidFinalKeyword {
            get {
                return ResourceManager.GetString("Error_AS010_InvalidFinalKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS011: missing integer value 的本地化字符串。
        /// </summary>
        internal static string Error_AS011_MissingIntLiteral {
            get {
                return ResourceManager.GetString("Error_AS011_MissingIntLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS012: missing &apos;{{&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS012_MissingOpenBrace {
            get {
                return ResourceManager.GetString("Error_AS012_MissingOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS013: field index must be in range (0, 268435456] 的本地化字符串。
        /// </summary>
        internal static string Error_AS013_InvalidFieldIndex {
            get {
                return ResourceManager.GetString("Error_AS013_InvalidFieldIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS014: missing &apos;:&apos; or &apos;|&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS014_MissingColonOrBar {
            get {
                return ResourceManager.GetString("Error_AS014_MissingColonOrBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS015: missing &apos;;&apos; or &apos;obsolete&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS015_MissingSemicolonOrObsoleteKeyword {
            get {
                return ResourceManager.GetString("Error_AS015_MissingSemicolonOrObsoleteKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS016: missing identifier or &apos;*&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS016_MissingIdentifierOrAsterisk {
            get {
                return ResourceManager.GetString("Error_AS016_MissingIdentifierOrAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS017: missing &apos;}}&apos; 的本地化字符串。
        /// </summary>
        internal static string Error_AS017_MissingCloseBrace {
            get {
                return ResourceManager.GetString("Error_AS017_MissingCloseBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS018: keyword &apos;private&apos; can only be used in nested types 的本地化字符串。
        /// </summary>
        internal static string Error_AS018_InvalidPrivateKeyword {
            get {
                return ResourceManager.GetString("Error_AS018_InvalidPrivateKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error: AS019: keyword &apos;protected&apos; can only be used in nested types 的本地化字符串。
        /// </summary>
        internal static string Error_AS019_InvalidProtectedKeyword {
            get {
                return ResourceManager.GetString("Error_AS019_InvalidProtectedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v0.1.6.7 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v0.1.6.7 unity 的本地化字符串。
        /// </summary>
        internal static string Version_Unity {
            get {
                return ResourceManager.GetString("Version_Unity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 warning: AS001: the memory size required for the structure must be greater than 0 的本地化字符串。
        /// </summary>
        internal static string Warning_AS001_InvalidMemorySize {
            get {
                return ResourceManager.GetString("Warning_AS001_InvalidMemorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 warning: AS002: package &apos;{0}&apos; will be referenced automatically, no need to manually reference again 的本地化字符串。
        /// </summary>
        internal static string Warning_AS002_UnnecessaryUsing {
            get {
                return ResourceManager.GetString("Warning_AS002_UnnecessaryUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 warning: AS003: the indexes of fields should be as continuous as possible 的本地化字符串。
        /// </summary>
        internal static string Warning_AS003_RequireContinuousIndex {
            get {
                return ResourceManager.GetString("Warning_AS003_RequireContinuousIndex", resourceCulture);
            }
        }
    }
}
