//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace accelc.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("accelc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 accel 的本地化字符串。
        /// </summary>
        internal static string AccelbufferFileExtension {
            get {
                return ResourceManager.GetString("AccelbufferFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accelbuffer.Injection 的本地化字符串。
        /// </summary>
        internal static string AccelbufferInjectionNamespace {
            get {
                return ResourceManager.GetString("AccelbufferInjectionNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accelbuffer.Memory 的本地化字符串。
        /// </summary>
        internal static string AccelbufferMemoryNamespace {
            get {
                return ResourceManager.GetString("AccelbufferMemoryNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accelbuffer 的本地化字符串。
        /// </summary>
        internal static string AccelbufferNamespace {
            get {
                return ResourceManager.GetString("AccelbufferNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 type #NAME#
        ///{  
        ///	
        ///	//序列化消息，会在序列化前调用，可以在这个方法设置字段的默认值，内部的代码请使用纯C#编写
        ///	.before
        ///	{
        ///
        ///	}
        ///
        ///	//序列化消息，会在反序列化后调用，内部的代码请使用纯C#编写
        ///	.after
        ///	{
        ///
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        internal static string AccelbufferTemplate {
            get {
                return ResourceManager.GetString("AccelbufferTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accelbuffer.Text 的本地化字符串。
        /// </summary>
        internal static string AccelbufferTextNamespace {
            get {
                return ResourceManager.GetString("AccelbufferTextNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 public void After() 的本地化字符串。
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [OnAfterDeserialization(Priority = 0)] 的本地化字符串。
        /// </summary>
        internal static string AfterAttr {
            get {
                return ResourceManager.GetString("AfterAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [] 的本地化字符串。
        /// </summary>
        internal static string ArraySuffix {
            get {
                return ResourceManager.GetString("ArraySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 public void Before() 的本地化字符串。
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [OnBeforeSerialization(Priority = 0)] 的本地化字符串。
        /// </summary>
        internal static string BeforeAttr {
            get {
                return ResourceManager.GetString("BeforeAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 break; 的本地化字符串。
        /// </summary>
        internal static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 case {0}: 的本地化字符串。
        /// </summary>
        internal static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [CheckRef] 的本地化字符串。
        /// </summary>
        internal static string CheckRef {
            get {
                return ResourceManager.GetString("CheckRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 class  的本地化字符串。
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [CompactLayout] 的本地化字符串。
        /// </summary>
        internal static string CompactLayout {
            get {
                return ResourceManager.GetString("CompactLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}() {{ }} 的本地化字符串。
        /// </summary>
        internal static string DefaultCtor {
            get {
                return ResourceManager.GetString("DefaultCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 default: 的本地化字符串。
        /// </summary>
        internal static string Defeault {
            get {
                return ResourceManager.GetString("Defeault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 int index = 0; 的本地化字符串。
        /// </summary>
        internal static string DefIndex {
            get {
                return ResourceManager.GetString("DefIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 public {0} Deserialize(ref StreamingIterator iterator) 的本地化字符串。
        /// </summary>
        internal static string DeserializeMethod {
            get {
                return ResourceManager.GetString("DeserializeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档需要&apos;--&apos;来结束 的本地化字符串。
        /// </summary>
        internal static string DocumentNotEnd {
            get {
                return ResourceManager.GetString("DocumentNotEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Encoding(Encoding.ASCII)] 的本地化字符串。
        /// </summary>
        internal static string EncodingASCII {
            get {
                return ResourceManager.GetString("EncodingASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Encoding(Encoding.Unicode)] 的本地化字符串。
        /// </summary>
        internal static string EncodingUnicode {
            get {
                return ResourceManager.GetString("EncodingUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Encoding(Encoding.UTF8)] 的本地化字符串。
        /// </summary>
        internal static string EncodingUTF8 {
            get {
                return ResourceManager.GetString("EncodingUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少&apos;public&apos;或&apos;internal&apos;修饰符 的本地化字符串。
        /// </summary>
        internal static string ExpectAccessKeyword {
            get {
                return ResourceManager.GetString("ExpectAccessKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少&apos;}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectCloseBrace {
            get {
                return ResourceManager.GetString("ExpectCloseBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .after方法缺少方法体 的本地化字符串。
        /// </summary>
        internal static string ExpectCShapCodeDotAfter {
            get {
                return ResourceManager.GetString("ExpectCShapCodeDotAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .before方法缺少方法体 的本地化字符串。
        /// </summary>
        internal static string ExpectCShapCodeDotBefore {
            get {
                return ResourceManager.GetString("ExpectCShapCodeDotBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少&apos;=&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectEquals {
            get {
                return ResourceManager.GetString("ExpectEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段定义缺少类型 的本地化字符串。
        /// </summary>
        internal static string ExpectFieldType {
            get {
                return ResourceManager.GetString("ExpectFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少标识符 的本地化字符串。
        /// </summary>
        internal static string ExpectIdentifier {
            get {
                return ResourceManager.GetString("ExpectIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少int32类型的值 的本地化字符串。
        /// </summary>
        internal static string ExpectInt32Literal {
            get {
                return ResourceManager.GetString("ExpectInt32Literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少&apos;{&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectOpenBrace {
            get {
                return ResourceManager.GetString("ExpectOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少&apos;;&apos;来结束 的本地化字符串。
        /// </summary>
        internal static string ExpectSemicolon {
            get {
                return ResourceManager.GetString("ExpectSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少&apos;type&apos;关键字 的本地化字符串。
        /// </summary>
        internal static string ExpectTypeKeyword {
            get {
                return ResourceManager.GetString("ExpectTypeKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 public {0} {1}; 的本地化字符串。
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FieldIndex({0})] 的本地化字符串。
        /// </summary>
        internal static string FieldIndex {
            get {
                return ResourceManager.GetString("FieldIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到文件：{0} 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径： 的本地化字符串。
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Fixed] 的本地化字符串。
        /// </summary>
        internal static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件生成成功 的本地化字符串。
        /// </summary>
        internal static string GenerateSuccessfully {
            get {
                return ResourceManager.GetString("GenerateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 index++; 的本地化字符串。
        /// </summary>
        internal static string IncreaseIndex {
            get {
                return ResourceManager.GetString("IncreaseIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [InitialMemorySize({0})] 的本地化字符串。
        /// </summary>
        internal static string InitialMemorySize {
            get {
                return ResourceManager.GetString("InitialMemorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 internal  的本地化字符串。
        /// </summary>
        internal static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的字符：&apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string InvalidChar {
            get {
                return ResourceManager.GetString("InvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字&apos;checkref&apos;不能在标记了&apos;compact&apos;的类型中使用 的本地化字符串。
        /// </summary>
        internal static string InvalidCheckRef {
            get {
                return ResourceManager.GetString("InvalidCheckRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字&apos;checkref&apos;不能标记不可空类型的字段 的本地化字符串。
        /// </summary>
        internal static string InvalidCheckrefKeyword {
            get {
                return ResourceManager.GetString("InvalidCheckrefKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;.ctor&apos;必须在标记了&apos;ref&apos;关键字的类型中使用 的本地化字符串。
        /// </summary>
        internal static string InvalidCtor {
            get {
                return ResourceManager.GetString("InvalidCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字&apos;utf8&apos;, &apos;unicode&apos;, &apos;ascii&apos;只能修饰&apos;char&apos;和&apos;string&apos;类型的字段 的本地化字符串。
        /// </summary>
        internal static string InvalidEncodingKeyword {
            get {
                return ResourceManager.GetString("InvalidEncodingKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有标记了&apos;ref&apos;关键字的类型才可以被标记为&apos;final&apos; 的本地化字符串。
        /// </summary>
        internal static string InvalidFinal {
            get {
                return ResourceManager.GetString("InvalidFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字&apos;fixed&apos;不能修饰非整数类型 的本地化字符串。
        /// </summary>
        internal static string InvalidFixedKeyword {
            get {
                return ResourceManager.GetString("InvalidFixedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法的标识符：&apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string InvalidIdentifier {
            get {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记：&apos;{0}&apos;无效 的本地化字符串。
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行号： 的本地化字符串。
        /// </summary>
        internal static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能同时定义多个命名空间 的本地化字符串。
        /// </summary>
        internal static string MultiNamespace {
            get {
                return ResourceManager.GetString("MultiNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可访问修饰符重复 的本地化字符串。
        /// </summary>
        internal static string MultipleAccessKeyword {
            get {
                return ResourceManager.GetString("MultipleAccessKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字：&apos;{0}&apos;重复 的本地化字符串。
        /// </summary>
        internal static string MultipleKeyword {
            get {
                return ResourceManager.GetString("MultipleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 namespace  的本地化字符串。
        /// </summary>
        internal static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} result = new {1}(); 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 result.{0} = iterator.NextAs{1}(); 的本地化字符串。
        /// </summary>
        internal static string NextAs {
            get {
                return ResourceManager.GetString("NextAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 result.{0} = iterator.NextAs{1}WithoutTag(Encoding.ASCII); 的本地化字符串。
        /// </summary>
        internal static string NextAsCharStringASCIICompact {
            get {
                return ResourceManager.GetString("NextAsCharStringASCIICompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 result.{0} = iterator.NextAs{1}WithoutTag(Encoding.Unicode); 的本地化字符串。
        /// </summary>
        internal static string NextAsCharStringUnicodeCompact {
            get {
                return ResourceManager.GetString("NextAsCharStringUnicodeCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 result.{0} = iterator.NextAs{1}WithoutTag(Encoding.UTF8); 的本地化字符串。
        /// </summary>
        internal static string NextAsCharStringUTF8Compact {
            get {
                return ResourceManager.GetString("NextAsCharStringUTF8Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 result.{0} = iterator.NextAs{1}WithoutTag(); 的本地化字符串。
        /// </summary>
        internal static string NextAsCompact {
            get {
                return ResourceManager.GetString("NextAsCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 result.{0} = iterator.NextAs&lt;{1}&gt;(); 的本地化字符串。
        /// </summary>
        internal static string NextAsComplex {
            get {
                return ResourceManager.GetString("NextAsComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 result.{0} = iterator.NextAsWithoutTag&lt;{1}&gt;(); 的本地化字符串。
        /// </summary>
        internal static string NextAsComplexCompact {
            get {
                return ResourceManager.GetString("NextAsComplexCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 result.{0} = iterator.NextAs{1}WithoutTag({2}); 的本地化字符串。
        /// </summary>
        internal static string NextAsIntCompact {
            get {
                return ResourceManager.GetString("NextAsIntCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumberFormat.Fixed 的本地化字符串。
        /// </summary>
        internal static string NumberFormat_Fixed {
            get {
                return ResourceManager.GetString("NumberFormat.Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumberFormat.Variant 的本地化字符串。
        /// </summary>
        internal static string NumberFormat_Variant {
            get {
                return ResourceManager.GetString("NumberFormat.Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 public  的本地化字符串。
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #NAME# 的本地化字符串。
        /// </summary>
        internal static string ReplaceString {
            get {
                return ResourceManager.GetString("ReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 return result; 的本地化字符串。
        /// </summary>
        internal static string ReturnResult {
            get {
                return ResourceManager.GetString("ReturnResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sealed  的本地化字符串。
        /// </summary>
        internal static string Sealed {
            get {
                return ResourceManager.GetString("Sealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ; 的本地化字符串。
        /// </summary>
        internal static string Semicolon {
            get {
                return ResourceManager.GetString("Semicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [System.Serializable] 的本地化字符串。
        /// </summary>
        internal static string Serializable {
            get {
                return ResourceManager.GetString("Serializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [SerializeBy(typeof({0}Serializer))] 的本地化字符串。
        /// </summary>
        internal static string SerializeBy {
            get {
                return ResourceManager.GetString("SerializeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 public void Serialize({0} obj, ref StreamingWriter writer) 的本地化字符串。
        /// </summary>
        internal static string SerializeMethod {
            get {
                return ResourceManager.GetString("SerializeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}Serializer 的本地化字符串。
        /// </summary>
        internal static string SerializerName {
            get {
                return ResourceManager.GetString("SerializerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 internal sealed class {0}Serializer : ITypeSerializer&lt;{1}&gt; 的本地化字符串。
        /// </summary>
        internal static string SerializerType {
            get {
                return ResourceManager.GetString("SerializerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iterator.SkipNext(); 的本地化字符串。
        /// </summary>
        internal static string SkipNext {
            get {
                return ResourceManager.GetString("SkipNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 struct  的本地化字符串。
        /// </summary>
        internal static string Struct {
            get {
                return ResourceManager.GetString("Struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 switch(index) 的本地化字符串。
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SyntaxError： 的本地化字符串。
        /// </summary>
        internal static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AccelbufferTemplate 的本地化字符串。
        /// </summary>
        internal static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命名空间的声明必须在类型之前 的本地化字符串。
        /// </summary>
        internal static string UnexpectedNamespace {
            get {
                return ResourceManager.GetString("UnexpectedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命名空间的引用必须在类型之前 的本地化字符串。
        /// </summary>
        internal static string UnexpectedUsing {
            get {
                return ResourceManager.GetString("UnexpectedUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法识别的字符：&apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UnknownChar {
            get {
                return ResourceManager.GetString("UnknownChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using  的本地化字符串。
        /// </summary>
        internal static string Using {
            get {
                return ResourceManager.GetString("Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v0.1.0.5 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 while(iterator.HasNext(out index)) 的本地化字符串。
        /// </summary>
        internal static string While {
            get {
                return ResourceManager.GetString("While", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 while(iterator.HasNext()) 的本地化字符串。
        /// </summary>
        internal static string WhileCompact {
            get {
                return ResourceManager.GetString("WhileCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 if (obj.{0} != null) 的本地化字符串。
        /// </summary>
        internal static string WriteValueCheckRef {
            get {
                return ResourceManager.GetString("WriteValueCheckRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue&lt;{0}&gt;({1}, obj.{2}); 的本地化字符串。
        /// </summary>
        internal static string WriteValueComplex {
            get {
                return ResourceManager.GetString("WriteValueComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue(obj.{1}); 的本地化字符串。
        /// </summary>
        internal static string WriteValueComplexCompact {
            get {
                return ResourceManager.GetString("WriteValueComplexCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue({0}, obj.{1}); 的本地化字符串。
        /// </summary>
        internal static string WriteValueFloatBool {
            get {
                return ResourceManager.GetString("WriteValueFloatBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue(obj.{0}); 的本地化字符串。
        /// </summary>
        internal static string WriteValueFloatBoolCompact {
            get {
                return ResourceManager.GetString("WriteValueFloatBoolCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue({0}, obj.{1}, {2}); 的本地化字符串。
        /// </summary>
        internal static string WriteValueInt {
            get {
                return ResourceManager.GetString("WriteValueInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue(obj.{0}, {1}); 的本地化字符串。
        /// </summary>
        internal static string WriteValueIntCompact {
            get {
                return ResourceManager.GetString("WriteValueIntCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue({0}, obj.{1}, Encoding.ASCII); 的本地化字符串。
        /// </summary>
        internal static string WriteValueStringASCII {
            get {
                return ResourceManager.GetString("WriteValueStringASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue(obj.{0}, Encoding.ASCII); 的本地化字符串。
        /// </summary>
        internal static string WriteValueStringASCIICompact {
            get {
                return ResourceManager.GetString("WriteValueStringASCIICompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue({0}, obj.{1}, Encoding.Unicode); 的本地化字符串。
        /// </summary>
        internal static string WriteValueStringUnicode {
            get {
                return ResourceManager.GetString("WriteValueStringUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue(obj.{0}, Encoding.Unicode); 的本地化字符串。
        /// </summary>
        internal static string WriteValueStringUnicodeCompact {
            get {
                return ResourceManager.GetString("WriteValueStringUnicodeCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue({0}, obj.{1}, Encoding.UTF8); 的本地化字符串。
        /// </summary>
        internal static string WriteValueStringUTF8 {
            get {
                return ResourceManager.GetString("WriteValueStringUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 writer.WriteValue(obj.{0}, Encoding.UTF8); 的本地化字符串。
        /// </summary>
        internal static string WriteValueStringUTF8Compact {
            get {
                return ResourceManager.GetString("WriteValueStringUTF8Compact", resourceCulture);
            }
        }
    }
}
